2024-05-31 09:50:40,564 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-05-31 09:50:40,564 WARN For [program:nginx], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
2024-05-31 09:50:40,564 WARN For [program:php-fpm], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
2024-05-31 09:50:40,566 INFO supervisord started with pid 1
2024-05-31 09:50:41,568 INFO spawned: 'nginx' with pid 7
2024-05-31 09:50:41,570 INFO spawned: 'php-fpm' with pid 8
2024-05-31 09:50:41,574 CRIT uncaptured python exception, closing channel <POutputDispatcher at 124678507081040 for <Subprocess at 124678525412432 with name nginx in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 09:50:41,574 WARN exited: nginx (exit status 1; not expected)
2024-05-31 09:50:41,718 CRIT uncaptured python exception, closing channel <POutputDispatcher at 124678523102672 for <Subprocess at 124678507484928 with name php-fpm in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 09:50:41,719 CRIT uncaptured python exception, closing channel <POutputDispatcher at 124678523102672 for <Subprocess at 124678507484928 with name php-fpm in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 09:50:42,720 INFO spawned: 'nginx' with pid 11
2024-05-31 09:50:42,720 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-05-31 09:50:42,725 CRIT uncaptured python exception, closing channel <POutputDispatcher at 124678527696096 for <Subprocess at 124678525412432 with name nginx in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 09:50:42,725 WARN exited: nginx (exit status 1; not expected)
2024-05-31 09:50:44,728 INFO spawned: 'nginx' with pid 12
2024-05-31 09:50:44,733 CRIT uncaptured python exception, closing channel <POutputDispatcher at 124678529594192 for <Subprocess at 124678525412432 with name nginx in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 09:50:44,733 WARN exited: nginx (exit status 1; not expected)
2024-05-31 09:50:47,737 INFO spawned: 'nginx' with pid 13
2024-05-31 09:50:47,742 CRIT uncaptured python exception, closing channel <POutputDispatcher at 124678507081040 for <Subprocess at 124678525412432 with name nginx in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 09:50:47,742 WARN exited: nginx (exit status 1; not expected)
2024-05-31 09:50:48,743 INFO gave up: nginx entered FATAL state, too many start retries too quickly
2024-05-31 09:53:02,882 WARN received SIGQUIT indicating exit request
2024-05-31 09:53:02,882 INFO waiting for php-fpm to die
2024-05-31 09:53:02,883 CRIT uncaptured python exception, closing channel <POutputDispatcher at 124678523102672 for <Subprocess at 124678507484928 with name php-fpm in state STOPPING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 09:53:02,883 CRIT uncaptured python exception, closing channel <POutputDispatcher at 124678523102672 for <Subprocess at 124678507484928 with name php-fpm in state STOPPING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 09:53:02,887 INFO stopped: php-fpm (exit status 0)
2024-05-31 09:53:20,288 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-05-31 09:53:20,289 WARN For [program:nginx], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
2024-05-31 09:53:20,289 WARN For [program:php-fpm], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
2024-05-31 09:53:20,290 INFO supervisord started with pid 1
2024-05-31 09:53:21,292 INFO spawned: 'nginx' with pid 6
2024-05-31 09:53:21,295 INFO spawned: 'php-fpm' with pid 7
2024-05-31 09:53:21,298 CRIT uncaptured python exception, closing channel <POutputDispatcher at 125785392477248 for <Subprocess at 125785390095040 with name nginx in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 09:53:21,299 WARN exited: nginx (exit status 1; not expected)
2024-05-31 09:53:21,336 CRIT uncaptured python exception, closing channel <POutputDispatcher at 125785390100512 for <Subprocess at 125785390099072 with name php-fpm in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 09:53:21,337 CRIT uncaptured python exception, closing channel <POutputDispatcher at 125785390100512 for <Subprocess at 125785390099072 with name php-fpm in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 09:53:22,339 INFO spawned: 'nginx' with pid 10
2024-05-31 09:53:22,340 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-05-31 09:53:22,346 CRIT uncaptured python exception, closing channel <POutputDispatcher at 125785392798928 for <Subprocess at 125785390095040 with name nginx in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 09:53:22,346 WARN exited: nginx (exit status 1; not expected)
2024-05-31 09:53:24,350 INFO spawned: 'nginx' with pid 11
2024-05-31 09:53:24,355 CRIT uncaptured python exception, closing channel <POutputDispatcher at 125785395078800 for <Subprocess at 125785390095040 with name nginx in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 09:53:24,355 WARN exited: nginx (exit status 1; not expected)
2024-05-31 09:53:27,360 INFO spawned: 'nginx' with pid 12
2024-05-31 09:53:27,365 CRIT uncaptured python exception, closing channel <POutputDispatcher at 125785389663632 for <Subprocess at 125785390095040 with name nginx in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 09:53:27,365 WARN exited: nginx (exit status 1; not expected)
2024-05-31 09:53:28,366 INFO gave up: nginx entered FATAL state, too many start retries too quickly
2024-05-31 10:04:27,131 WARN received SIGQUIT indicating exit request
2024-05-31 10:04:27,131 INFO waiting for php-fpm to die
2024-05-31 10:04:27,131 CRIT uncaptured python exception, closing channel <POutputDispatcher at 125785390100512 for <Subprocess at 125785390099072 with name php-fpm in state STOPPING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 10:04:27,132 CRIT uncaptured python exception, closing channel <POutputDispatcher at 125785390100512 for <Subprocess at 125785390099072 with name php-fpm in state STOPPING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 10:04:27,136 INFO stopped: php-fpm (exit status 0)
2024-05-31 10:04:42,175 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-05-31 10:04:42,175 WARN For [program:nginx], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
2024-05-31 10:04:42,175 WARN For [program:php-fpm], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
2024-05-31 10:04:42,177 INFO supervisord started with pid 1
2024-05-31 10:04:43,180 INFO spawned: 'nginx' with pid 7
2024-05-31 10:04:43,181 INFO spawned: 'php-fpm' with pid 8
2024-05-31 10:04:43,184 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131864472293200 for <Subprocess at 131864472721440 with name nginx in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 10:04:43,185 WARN exited: nginx (exit status 1; not expected)
2024-05-31 10:04:43,219 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131864472297952 for <Subprocess at 131864472726288 with name php-fpm in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 10:04:43,219 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131864472297952 for <Subprocess at 131864472726288 with name php-fpm in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 10:04:44,222 INFO spawned: 'nginx' with pid 11
2024-05-31 10:04:44,222 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-05-31 10:04:44,226 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131864473203152 for <Subprocess at 131864472721440 with name nginx in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 10:04:44,226 WARN exited: nginx (exit status 1; not expected)
2024-05-31 10:04:46,229 INFO spawned: 'nginx' with pid 12
2024-05-31 10:04:46,234 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131864473965184 for <Subprocess at 131864472721440 with name nginx in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 10:04:46,234 WARN exited: nginx (exit status 1; not expected)
2024-05-31 10:04:49,238 INFO spawned: 'nginx' with pid 13
2024-05-31 10:04:49,243 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131864472128352 for <Subprocess at 131864472721440 with name nginx in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 10:04:49,244 WARN exited: nginx (exit status 1; not expected)
2024-05-31 10:04:50,245 INFO gave up: nginx entered FATAL state, too many start retries too quickly
2024-05-31 10:12:12,780 WARN received SIGQUIT indicating exit request
2024-05-31 10:12:12,780 INFO waiting for php-fpm to die
2024-05-31 10:12:12,781 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131864472297952 for <Subprocess at 131864472726288 with name php-fpm in state STOPPING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 10:12:12,781 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131864472297952 for <Subprocess at 131864472726288 with name php-fpm in state STOPPING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.12/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.12/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.12/site-packages/supervisor/loggers.py|doRollover|264])
2024-05-31 10:12:12,785 INFO stopped: php-fpm (exit status 0)
